# Describes the format for available component services

set_pet_location:
  description: Set pet location
  fields:
    pet_name:
      description: Name of pet
      example: My_cat
    location:
      description: Pet location (Inside or Outside)
      example: inside
